#!/usr/bin/env bash

# When multiple options list them and add shift support to go backwards
bind 'TAB:menu-complete'
bind '"\e[Z": menu-complete-backward'

# Show list of all possible options
bind 'set show-all-if-ambiguous on'

# Will auto complete until options diff on first tab
bind "set menu-complete-display-prefix on"
